export const BREATHING_ICONS = Object.freeze({
  "Água": "resp_agua.webp",
  "Amor": "resp_amor.webp",
  "Aranha": "resp_aranha.webp",
  "Areia": "resp_areia.webp",
  "Besta": "resp_besta.webp",
  "Cerejeira": "resp_cerejeira.webp",
  "Chamas": "resp_chamas.webp",
  "Corvo": "resp_corvo.webp",
  "Cristal": "resp_cristal.webp",
  "Dragão": "resp_dragao.webp",
  "Eclipse": "resp_eclipse.webp",
  "Flores": "resp_flor.webp",
  "Grama": "resp_grama.webp",
  "Insetos": "resp_inseto.webp",
  "Lobo": "resp_lobo.webp",
  "Lua": "resp_lua.webp",
  "Luz": "resp_luz.webp",
  "Madeira": "resp_madeira.webp",
  "Magma": "resp_magma.webp",
  "Metal": "resp_metal.webp",
  "Neve": "resp_neve.webp",
  "Névoa": "resp_nevoa.webp",
  "Pedra": "resp_pedra.webp",
  "Raposa": "resp_raposa.webp",
  "Sangue": "resp_sangue.webp",
  "Serpente": "resp_serpente.webp",
  "Sol": "resp_sol.webp",
  "Som": "resp_som.webp",
  "Sombras": "resp_sombras.webp",
  "Sonhos": "resp_sonhos.webp",
  "Tempo": "resp_tempo.webp",
  "Tigre": "resp_tigre.webp",
  "Trovão": "resp_trovao.webp",
  "Vagalume": "resp_vagalume.webp",
  "Veneno": "resp_veneno.webp",
  "Vento": "resp_vento.webp",
});

export function breathingIconPath(breathing) {
  const file = BREATHING_ICONS[breathing];
  return file ? `modules/night-assassins-csb-automation/assets/icons/breathing/${file}` : null;
}
